# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build and push docker images
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: aryanshrana/polybot
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: 1.1.1-${{github.run_number}}
    - name: Checkout polybot-configs
      uses: actions/checkout@v3
      with:
         repository: Devs-At-Work/polybot-configs
         ref: main
         path: ./polybot-configs

    # - name: clone
      # run: |
        # git clone https://github.com/Devs-At-Work/polybot-configs.git

    - name: Update deployment YAML and commit changes
      run: |
        # cd polybot-configs
        # Install yq
        sudo wget https://github.com/mikefarah/yq/releases/download/v4.12.1/yq_linux_amd64 -O /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq

        # Update the image tag in the deployment YAML file
        yq e -i '.spec.template.spec.containers[0].image = "aryanshrana/polybot:1.1.1-${{ github.run_number }}"' ./dev/polybot-deployment.yaml

        # Commit and push changes
        # cd /github/workspace/polybot-configs

        # Commit and push changes
        # git config user.name "Aryansh"
        # git config user.email "500093038@stu.upes.ac.in"
        # git add .
        # git commit -m "Update image tag in polybot-deployment.yaml"
        # git push

